services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      retries: 5

  # drizzle
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faire_auth
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d faire_auth"]
      interval: 3s
      retries: 5

  postgres-kysely:
    image: postgres:latest
    container_name: postgres-kysely
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faire_auth
    ports:
      - "127.0.0.1:5436:5432"
    volumes:
      - postgres-kysely_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d faire_auth"]
      interval: 3s
      retries: 5

  postgres-kysely2:
    image: postgres:latest
    container_name: postgres-kysely2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faire_auth
    ports:
      - "127.0.0.1:5438:5432"
    volumes:
      - postgres-kysely2_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d faire_auth"]
      interval: 3s
      retries: 5

  postgres-prisma:
    image: postgres:latest
    container_name: postgres-prisma
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faire_auth
    ports:
      - "127.0.0.1:5437:5432"
    volumes:
      - postgres-prisma_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d faire_auth"]
      interval: 3s
      retries: 5

  # Drizzle tests
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: faire_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 3s
      retries: 5

  mysql-kysely:
    image: mysql:latest
    container_name: mysql-kysely
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: faire_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql-kysely_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 3s
      retries: 5

  mysql-prisma:
    image: mysql:latest
    container_name: mysql-prisma
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: faire_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - mysql-prisma_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 3s
      retries: 5

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    environment:
      MSSQL_SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'Password123!' -Q 'SELECT 1'"]
      interval: 5s
      retries: 10

volumes:
  mongodb_data:
  postgres_data:
  postgres-kysely_data:
  postgres-kysely2_data:
  postgres-prisma_data:
  mysql_data:
  mssql_data:
  mysql-kysely_data:
  mysql-prisma_data:
