import {
	changeEmailRoute,
	changePasswordRoute,
	deleteUserCallbackRoute,
	deleteUserRoute,
	errorRoute,
	getAccessTokenRoute,
	getAccountInfoRoute,
	getOAuthCallbackRoute,
	getSessionRoute,
	linkAccountRoute,
	listAccountsRoute,
	listSessionsRoute,
	okRoute,
	postOAuthCallbackRoute,
	refreshAccessTokenRoute,
	requestPasswordResetCallbackRoute,
	requestPasswordResetRoute,
	resetPasswordRoute,
	revokeOtherSessionsRoute,
	revokeSessionRoute,
	revokeSessionsRoute,
	sendVerificationEmailRoute,
	setPasswordRoute,
	signInEmailRoute,
	signInSocialRoute,
	signOutRoute,
	signUpEmailRoute,
	unlinkAccountRoute,
	updateUserRoute,
	verifyEmailRoute,
} from "./routes";
import { Routes } from "@faire-auth/core/static";

export const staticConfigMap = {
	[Routes.SET_PASSWORD]: setPasswordRoute,
	[Routes.CHANGE_EMAIL]: changeEmailRoute,
	[Routes.CHANGE_PASSWORD]: changePasswordRoute,
	[Routes.DELETE_USER]: deleteUserRoute,
	[Routes.DELETE_USER_CALLBACK]: deleteUserCallbackRoute,
	[Routes.ERROR]: errorRoute,
	[Routes.GET_ACCESS_TOKEN]: getAccessTokenRoute,
	[Routes.GET_ACCOUNT_INFO]: getAccountInfoRoute,
	[Routes.GET_SESSION]: getSessionRoute,
	[Routes.LINK_ACCOUNT]: linkAccountRoute,
	[Routes.LIST_ACCOUNTS]: listAccountsRoute,
	[Routes.LIST_SESSIONS]: listSessionsRoute,
	[Routes.OAUTH_CALLBACK_GET]: getOAuthCallbackRoute,
	[Routes.OAUTH_CALLBACK_POST]: postOAuthCallbackRoute,
	[Routes.OK]: okRoute,
	[Routes.REFRESH_ACCESS_TOKEN]: refreshAccessTokenRoute,
	[Routes.REQUEST_PASSWORD_RESET]: requestPasswordResetRoute,
	[Routes.REQUEST_PASSWORD_RESET_CALLBACK]: requestPasswordResetCallbackRoute,
	[Routes.RESET_PASSWORD]: resetPasswordRoute,
	[Routes.REVOKE_OTHER_SESSIONS]: revokeOtherSessionsRoute,
	[Routes.REVOKE_SESSION]: revokeSessionRoute,
	[Routes.REVOKE_SESSIONS]: revokeSessionsRoute,
	[Routes.SEND_VERIFICATION_EMAIL]: sendVerificationEmailRoute,
	[Routes.SIGN_IN_EMAIL]: signInEmailRoute,
	[Routes.SIGN_IN_SOCIAL]: signInSocialRoute,
	[Routes.SIGN_OUT]: signOutRoute,
	[Routes.SIGN_UP_EMAIL]: signUpEmailRoute,
	[Routes.UNLINK_ACCOUNT]: unlinkAccountRoute,
	[Routes.UPDATE_USER]: updateUserRoute,
	[Routes.VERIFY_EMAIL]: verifyEmailRoute,
};
